server:
  port: 80
  context-path: /base
spring:
  application:
    name: springboot-base
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guo503/springboot-base.git #配置git仓库的地址
          username: guo503
          password: gs503178
          search-paths: gs-tsyj #配置git仓库下的相对地址，可以配置多个，用 , 分割
      label:  master        #配置文件所在的分支
      profile: dev
  datasource:
    name: test
    url: jdbc:mysql://106.13.94.134:3306/tsyj?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
    username: root
    password: 503178@gs
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      initial-size: 2
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      testOnReturn: false

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 106.13.94.134
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: gs503178
    timeout: 5000

mybatis:
  mapper-locations: classpath*:mapper/*.xml
