binlog:
  mysql:
    hosts:
      - name: test-db
        host: 115.29.231.136
        port: 3306
        username: maxwell
        password: 123456@Gs
        timeOffset: 28800000


app:
  id: springboot-base # 使用的 Apollo 的项目（应用）编号
  bootstrap:
    enabled: true # 是否开启 Apollo 配置预加载功能。默认为 false。
    eagerLoad:
      enable: true # 是否开启 Apollo 支持日志级别的加载时机。默认为 false。
env: dev

